adding tool to uppdate proxy service on previous blocks
rsksmart/rsk-explorer-api pull request #76
Opened 2022-05-25 14:35 UTC by kayseriiovlabs

adding tool to update exiting addresses with proxies EIP1167 and add masterCopy Field on mongodb.

this script should be run with `node dist/tools/updateAddressWithEIP1167.js`, this script it's to update the already exiting address that accomplish with EIP1167 proxy standard and add `masterCopy` field for the one's that accomplish with the requirements, so we can display that fields on the front end `rsk-explorer`

2022-05-30 14:23 UTC, ilanolkies requested changes
LGTM. Two things:
1. We need to refactor duplicated code
2. How is the script run? We need to add some docs to understand HOW and WHEN this should be run

2022-05-30 14:23 UTC, ilanolkies commented on src/tools/updateAddressWithEIP1167.js
> +  const implementationAddress = bytecode.replace(EIP_1167_PREFIX, '').replace(EIP_1167_SUFFIX, '')
This is duplicated with https://github.com/rsksmart/rsk-contract-parser/pull/17/files#diff-820e8d6807a80deaa63c82200d09d6d3289226dec71b20de1e15c2ba43482a1bR174

2022-05-31 13:17 UTC, kayseriiovlabs commented on src/tools/updateAddressWithEIP1167.js
> +  const collectionWithProxies = await collections.Addrs.find({code: { $regex: /^(0x)?363d3d373d3d3d363d73[a-f0-9]{40}5af43d82803e903d91602b57fd5bf3$/, $options: 'i' }}).toArray()
in this case it's not duplicated because i need the regex and the method it's returning a boolean instead of the regex itself

2022-05-31 15:10 UTC, ilanolkies commented on src/tools/updateAddressWithEIP1167.js
> +  const collectionWithProxies = await collections.Addrs.find({code: { $regex: /^(0x)?363d3d373d3d3d363d73[a-f0-9]{40}5af43d82803e903d91602b57fd5bf3$/, $options: 'i' }}).toArray()
The substrings are duplicated

2022-05-31 15:15 UTC, ilanolkies commented on src/tools/updateAddressWithEIP1167.js
> +  const collectionWithProxies = await collections.Addrs.find({code: { $regex: /^(0x)?363d3d373d3d3d363d73[a-f0-9]{40}5af43d82803e903d91602b57fd5bf3$/, $options: 'i' }}).toArray()
`${EIP_1167_PREFIX}[a-f0-9]{40}${EIP_1167_SUFFIX}$`

2022-06-01 14:33 UTC, ilanolkies approved these changes
Perfect 👍

2022-06-01 14:33 UTC, merged